### ISSUE TITLE
Transfer to @flash-center

### ISSUE THREAD

**Issue by jtlaune** [flash-center/opacplot2#8]
@flash-center's fork has been transferred to a private account. It should now be possible to transfer this fork to the ownership of @flash-center.

After the transfer, I will attempt to transfer all of the old issues from the @flash-center's old fork to this one using [this tool](https://github.com/google/github-issue-mover).

**Comment by rth** [comment]
@jtlaune  That's great, thanks! OK just tried to make the transfer and it still does not work because, the only option there is consists in,
> Transfer this repository to another user or to an organization where you have the ability to create repositories. 

This is frustrating. I obviously can't create repos at flash-center, and so have to transfer it to a administrator user account. I wish github would make things simpler: never though it could be so complicated to just move the root fork under an organization account on github. 

Anyway, I just initiated a transfer to @kweide  account, since  @tzeferacos has already another fork of this repository.  Hopefully this would work...

**Comment by jtlaune** [comment]
@rth opacplot2 is now owned by the @flash-center! Thank you for the help. I will coordinate with @tzeferacos to transfer the old issues and then I can close this.

**Comment by rth** [comment]
Wonderful!  It might also be worth creating an announcement issue at https://github.com/tzeferacos/opacplot_deprecated to let people subscribed to notifications from that repo know about the migration..
